### ISSUE TITLE
Tailwind 3 config for umbrella app

### ISSUE THREAD

**Issue by pzingg** [sergiotapia/golden#2]
Thank you for this project.

I was able to use it slightly modified in an umbrella project using Tailwind 3.

For TW3 you don’t need the “mode” parameter (it’s always JIT), and you change “purge” to “content”, in tailwind.config.js. 

Also, I had a slightly different “assets.deploy” mix alias, that runs “yarn install” and “npx tailwindcss” in the assets directory, as well as running esbuild with application name.

**Comment by sergiotapia** [comment]
Thanks I'll update this project!
